micronaut:
  application:
    name: hello-micronaut

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  info:
      enable: true
      sensitive: false
      details-visible: ANONYMOUS


consul:
  client:
    registration:
      enabled: false
      check:
        http: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

